sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa application/json
    activate server
    server-->>browser: status code: 201 Created
    deactivate server

    Note right of browser: The server does not request a redirect, the browser stays on the same page and does not send any more HTTP requests
